DATA_INTERVAL_MINUTES = 60
TEMP_MIN, TEMP_MAX = -10, 55
HUMIDITY_MIN, HUMIDITY_MAX = 0, 100
WIND_MIN, WIND_MAX = 0, 250
PRESSURE_MIN, PRESSURE_MAX = 870, 1085
WIND_DIRECTION_MIN, WIND_DIRECTION_MAX = 0, 360
SOLAR_RADIATION_MIN, SOLAR_RADIATION_MAX = 0, 1400
CLOUD_COVER_MIN, CLOUD_COVER_MAX = 0, 100
MONSOON_MONTHS = {6, 7, 8, 9}
RAIN_THRESHOLD_MONSOON = 80
RAIN_THRESHOLD_DRY = 30
SILENT_GAP_MINUTES = 120
FLATLINE_COUNT = 6
NUM_NEIGHBORS = 3
MISMATCH_THRESHOLD_MM = 5.0
TEMP_SPIKE_CHANGE = 10.0
PRESSURE_JUMP_CHANGE = 12.0
HUMIDITY_SPIKE_CHANGE = 35.0
TEMP_NEIGHBOR_DIFF = 6.0
PRESSURE_NEIGHBOR_DIFF = 8.0
HUMIDITY_NEIGHBOR_DIFF = 25.0
REPEAT_COUNT = 3
ML_CONTAMINATION = 0.03
ML_RANDOM_STATE = 42
REGION_CONTAMINATION = {'coastal': 0.05, 'desert': 0.02, 'default': 0.03}
HEALTH_SCORE_WINDOW_DAYS = 7
HEALTH_SCORE_PENALTY_PER_ANOMALY = 5
ALERT_CRITICAL_CONFIDENCE = 66
ALERT_MEDIUM_CONFIDENCE = 33
RETRAIN_INTERVAL_DAYS = 180
TRUST_QUARANTINE_CONFIDENCE = 66
TRUST_CAUTION_CONFIDENCE = 33

# Phase 2 Live Meteorological Config
LIVE_METEO_ENABLED = True
LIVE_POLL_INTERVAL_SECONDS = 300
OPEN_METEO_TIMEOUT_SECONDS = 10
LIVE_ALERT_COOLDOWN_SECONDS = 1800
STATION_HISTORY_MAX_LEN = 200

def seasonal_rain_threshold(month: int) -> float:

    return RAIN_THRESHOLD_MONSOON if month in MONSOON_MONTHS else RAIN_THRESHOLD_DRY

def get_contamination(region: str = 'default') -> float:
    return REGION_CONTAMINATION.get(region, REGION_CONTAMINATION['default'])

